name: data_source
description: Data source package.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  moor: ^3.3.1
  sqlite3_flutter_libs: ^0.2.0
  path_provider: ^1.6.14
  path: ^1.7.0
  pos_domain:
    path: ../pos_domain

dev_dependencies:
  moor_generator: ^3.3.1
  build_runner: ^1.10.2
