const Map<String, String> englishLocale = {
  "label-information": "Information",
  "label-items": "Items",
  "label-receipts": "Receipts",
  "label-reports": "Reports",
  "label-setting": "Setting",
  "label-menu": "Menu",
  "label-products": "Products",
  "label-categories": "Categories",
  "label-discounts": "Discounts",
  "label-taxes": "Taxes",
  "label-create-product": "Create Product",
  "label-update-product": "Update Product",
  "label-create-category": "Create Category",
  "label-update-category": "Update Category",
  "label-create-discount": "Create Discount",
  "label-update-discount": "Update Discount",
  "label-create-tax": "Create Tax",
  "label-update-tax": "Update Tax",
  "label-create-variant": "Create Variant",
  "label-update-variant": "Update Variant",
  "label-product": "Product",
  "label-category": "Category",
  "label-discount": "Discount",
  "label-tax": "Tax",
  "label-name": "Name",
  "label-representation-color": "Representation Color",
  "label-save": "Save",
  "label-cancel": "Cancel",
  "label-delete": "Delete",
  "label-value": "Value",
  "label-price": "Price",
  "label-cost": "Cost",
  "label-barcode": "Barcode",
  "label-status": "Status",
  "label-available": "Available",
  "label-not-available": "Not Available",
  "label-variants": "Variants",
  "label-product-image": "Product Image",
  "label-add": "Add",
  "label-choose": "Choose",
  "label-choose-category": "Choose Category",
  "label-choose-discount": "Choose Discount",
  "label-choose-tax": "Choose Tax",
  "label-done": "Done",
  "label-all-products": "All Products",
  "label-charge": "Charge",
  "label-shopping-cart": "Shopping Cart",
  "label-pay": "Pay",
  "label-payment": "Payment",
  "label-skip": "Skip",
  "label-subtotal": "Subtotal",
  "label-total-price": "Total Price",
  "label-change": "Change",
  "label-ok": "OK",
  "label-weekly-sales": "Weekly Sales",
  "label-recent-sales": "Recent Sales",
  "label-no-sale-today": "No sales today",
  "label-sale-items": "Sale Items",
  "label-quantity": "Quantity",
  "label-new-sale": "New Sale",
  "label-remove": "Remove",
  "label-language": "Language",
  "label-total-sale": "Total Sale",
  "label-total-profit": "Total Profit",
  "label-sale-by-category": "Sale By Category",
  "label-monthly-sale": "Monthly Sales",
  "hint-enter-category-name": "Enter category name",
  "hint-enter-discount-name": "Enter discount name",
  "hint-enter-discount-value": "Enter discount value",
  "hint-enter-tax-name": "Enter tax name",
  "hint-enter-tax-value": "Enter tax value",
  "hint-enter-product-name": "Enter product name",
  "hint-choose-category": "Choose category",
  "hint-enter-product-price": "Enter product price",
  "hint-enter-product-cost": "Enter product cost",
  "hint-enter-product-barcode": "Enter product barcode",
  "hint-enter-variant-name": "Enter variant name",
  "hint-enter-variant-price": "Enter variant price",
  "hint-enter-variant-cost": "Enter variant cost",
  "hint-enter-variant-barcode": "Enter variant barcode",
  "hint-search": "Search...",
  "hint-pay-price": "Pay price",
  "error-input-category-name": "Please enter category name.",
  "error-input-discount-name": "Please enter discount name.",
  "error-input-discount-value": "Please enter discount value.",
  "error-input-tax-name": "Please enter tax name.",
  "error-input-tax-value": "Please enter tax value.",
  "error-input-product-name": "Please enter product name.",
  "error-input-choose-category": "Please choose category.",
  "error-input-product-price": "Please enter product price.",
  "error-input-variant-name": "Please enter variant name.",
  "error-input-variant-price": "Please enter variant price.",
  "error-barcode-duplicate": "Barcode duplicated.",
  "msg-confirm-delete": "Are you sure to delete?",
  "msg-skip-pay-price": "Are you sure to skip and complete payment?",
  "msg-remove-all": "Are you sure to remove all?",
};

const Map<String, String> myanmarLocale = {
  "label-information": "အချက်အလက်များ",
  "label-items": "စာရင်းများ",
  "label-receipts": "အရောင်းစာရင်းများ",
  "label-reports": "စာရင်းချုပ်",
  "label-setting": "ပြင်ဆင်မှုများ",
  "label-menu": "Menu",
  "label-products": "ကုန်ပစ္စည်းများ",
  "label-categories": "အမျိုးအစားများ",
  "label-discounts": "လျှော့စျေးများ",
  "label-taxes": "အခွန်နှုန်းများ",
  "label-create-product": "ကုန်ပစ္စည်း ထည့်မည်",
  "label-update-product": "ကုန်ပစ္စည်း ပြင်မည်",
  "label-create-category": "အမျိုးအစား ထည့်မည်",
  "label-update-category": "အမျိုးအစား ပြင်မည်",
  "label-create-discount": "လျှော့စျေး ထည့်မည်",
  "label-update-discount": "လျှော့စျေး ပြင်မည်",
  "label-create-tax": "အခွန်နှုန်း ထည့်မည်",
  "label-update-tax": "အခွန်နှုန်း ပြင်မည်",
  "label-create-variant": "မူကွဲ ထည့်မည်",
  "label-update-variant": "မူကွဲ ပြင်မည်",
  "label-product": "ကုန်ပစ္စည်း",
  "label-category": "အမျိုးအစား",
  "label-discount": "လျှော့စျေး",
  "label-tax": "အခွန်နှုန်း",
  "label-name": "နာမည်",
  "label-representation-color": "ကိုယ်စားပြု အရောင်",
  "label-save": "သိမ်းမည်",
  "label-cancel": "မလုပ်ပါ",
  "label-delete": "ဖျက်မည်",
  "label-value": "တန်ဖိုး",
  "label-price": "စျေးနှုန်း",
  "label-cost": "ကုန်ကျစရိတ်",
  "label-barcode": "ဘားကုဒ်",
  "label-status": "Status",
  "label-available": "ရရှိနိုင်",
  "label-not-available": "မရရှိနိုင်ပါ",
  "label-variants": "မူကွဲများ",
  "label-product-image": "ကုန်ပစ္စည်းပုံ",
  "label-add": "အသစ်",
  "label-choose": "ရွေးချယ်ပါ",
  "label-choose-category": "အမျိုးအစားရွေးပါ",
  "label-choose-discount": "လျှော့စျေး ရွေးပါ",
  "label-choose-tax": "အခွန်နှုန်း ရွေးပါ",
  "label-done": "ပြီးပြီ",
  "label-all-products": "ကုန်ပစ္စည်းအားလုံး",
  "label-charge": "ငွေရှင်းမည်",
  "label-shopping-cart": "စျေးခြင်းတောင်း",
  "label-pay": "ပေးမည်",
  "label-payment": "ငွေပေးချေမှု",
  "label-skip": "Skip",
  "label-subtotal": "စုစုပေါင်း",
  "label-total-price": "ကျသင့်ငွေ",
  "label-change": "ပြန်အမ်းငွေ",
  "label-ok": "OK",
  "label-weekly-sales": "ယခုတစ်ပတ်အရောင်းစာရင်း",
  "label-recent-sales": "ယနေ့အရောင်းစာရင်း",
  "label-no-sale-today": "ယနေ့အရောင်းမရှိသေးပါ",
  "label-sale-items": "အရောင်းပစ္စည်းများ",
  "label-quantity": "အရေအတွက်",
  "label-new-sale": "အသစ်ရောင်းမည်",
  "label-remove": "ဖျက်မည်",
  "label-language": "ဘာသာစကား",
  "label-total-sale": "စုစုပေါင်းရောင်းရငွေ",
  "label-total-profit": "စုစုပေါင်းအမြတ်",
  "label-sale-by-category": "အမျိုးအစားလိုက် ရောင်းချမှု",
  "label-monthly-sale": "လစဉ်ရောင်း ရောင်းချမှု",
  "hint-enter-category-name": "အမျိုးအစား နာမည်",
  "hint-enter-discount-name": "လျှော့စျေး နာမည်",
  "hint-enter-discount-value": "လျှော့စျေး တန်ဖိုး",
  "hint-enter-tax-name": "အခွန်နှုန်း နာမည်",
  "hint-enter-tax-value": "အခွန်နှုန်း တန်ဖိုး",
  "hint-enter-product-name": "ကုန်ပစ္စည်း နာမည်",
  "hint-choose-category": "အမျိုးအစားရွေးပါ",
  "hint-enter-product-price": "ကုန်ပစ္စည်း စျေးနှုန်း",
  "hint-enter-product-cost": "ကုန်ပစ္စည်း ကုန်ကျစရိတ်",
  "hint-enter-product-barcode": "ကုန်ပစ္စည်း ဘားကုဒ်",
  "hint-enter-variant-name": "မူကွဲ နာမည်",
  "hint-enter-variant-price": "မူကွဲ စျေးနှုန်း",
  "hint-enter-variant-cost": "မူကွဲ ကုန်ကျစရိတ်",
  "hint-enter-variant-barcode": "မူကွဲ ဘားကုဒ်",
  "hint-search": "ရှာမည်...",
  "hint-pay-price": "ပေးသည့်ငွေ",
  "error-input-category-name": "အမျိုးအစား နာမည်ထည့်ပါ။",
  "error-input-discount-name": "လျှော့စျေး နာမည်ထည့်ပါ။",
  "error-input-discount-value": "လျှော့စျေး တန်ဖိုးထည့်ပါ။",
  "error-input-tax-name": "အခွန်နှုန်း နာမည်ထည့်ပါ။",
  "error-input-tax-value": "အခွန်နှုန်း တန်ဖိုးထည့်ပါ။",
  "error-input-product-name": "ကုန်ပစ္စည်း နာမည်ထည့်ပါ။",
  "error-input-choose-category": "အမျိုးအစားရွေးပါ။",
  "error-input-product-price": "ကုန်ပစ္စည်း စျေးနှုန်းထည့်ပါ။",
  "error-input-variant-name": "မူကွဲ နာမည်ထည့်ပါ။",
  "error-input-variant-price": "မူကွဲ စျေးနှုန်းထည့်ပါ။",
  "error-barcode-duplicate": "ဘားကုဒ်ရှိပြီးသားဖြစ်နေပါသည်။",
  "msg-confirm-delete": "ဖျက်မှာသေချာလား?",
  "msg-skip-pay-price": "သင်ကျော်သွားဖို့သေချာပါသလား?",
  "msg-remove-all": "အားလုံးဖျက်မှာသေချာလား?",
};